### PR TITLE
Removed adbapi and it's underlying use of threads

### PR DESCRIPTION
**Pull request by ssvsergeyev**

### CODE REVIEW

**Comment by cluther** [comment]
I don't see how not using threads addresses ZEN-19220. Threads were making this asynchronous. Maybe not ideally asynchronous, but at least better than full blocking.

**Comment by ssvsergeyev** [comment]
Using threads as we talking earlier is problem when try to stop task with signal.
Right now it use deferred and run in a main thread. So we may kill it from zenpython.

**Comment by ssvsergeyev** [comment]
Please take a look at https://github.com/zenoss/ZenPacks.zenoss.MySqlMonitor/commit/faa5330bb08b2778e87186d6aff8e4c95667b96a with a sample watchdog.

**Comment by cluther** [comment]
Adding a watchdog to zenpython doesn't mean we can have plugins performing blocking IO.

A plugin that hits a timeout due to running blocking IO is just an extreme case. Even if that plugin was functioning as designed and getting its data back "quickly" it would be blocking the reactor too much and affecting zenpython's ability to get other tasks done.

If the threaded implementation of MySqlMonitor's plugins need to timeout for some reason, they should be implementing the timeout safely rather than having zenpython implement it unsafely.

**Comment by cluther** [comment]
Also, unless I'm misunderstanding something in faa5330 it would seem that the guard implementation wouldn't work. Since the blocking IO used in MySQLdb is synchronous the reactor won't be able to perform the callLater on the guard until the MySQLdb calls return anyway.

**Pull request closed without merging**
